version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    environment:
        - cluster.name=smart-lock-demo
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
        - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
        - SA_PASSWORD=My_password123
        - ACCEPT_EULA=Y
  smartlockdemo.webapi:
    image: ${DOCKER_REGISTRY-}smartlockdemowebapi
    container_name: smartlockdemo.webapi
    build:
      context: .
      dockerfile: SmartLockDemo.WebAPI/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - MSSQL_CONNECTION_STRING=Server=sqlserver;Database=SmartLockDemo;User=sa;Password=My_password123;
        - ELASTICSEARCH_URI=http://elasticsearch:9200/
    depends_on:
      - sqlserver
    ports:
        - "8000:80"
